#!/bin/bash
# WF 2020-06-03
PYTHON_VERSION=$(python --version)
if [[ $PYTHON_VERSION = "Python 3"* ]]
then
	PYTHON="python"
else
	PYTHON="python3"
fi
echo "Selected $PYTHON as python path"
$PYTHON -m unittest discover