# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  corpus_db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: install ConferenceCorpus
        run: pip install ConferenceCorpus
      - name: download ConferenceCorpus database
        run: python scripts/get_cc_db.py
      - uses: actions/upload-artifact@v3
        with:
          name: ConferenceCorpus
          path: ~/.conferencecorpus/EventCorpus.db
          retention-days: 1
  test:
    runs-on: ubuntu-latest
    needs: [corpus_db]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: ConferenceCorpus
        path: ~/.conferencecorpus/
    - name: Check artifact
      run: ls ~/.conferencecorpus/
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies 
      run: |
        scripts/install
    - name: get SMW backups of OPENRESEARCH and Clone
      run: |
        scripts/getbackup
    - name: get offline data
      run: |
        scripts/getofflinedata
    - name: Run tests
      run: |
        scripts/test
  quality:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install pylint
        run: |
          pip install pylint
      - name: Code Quality Analysis
        run: |
          pylint kglConferenceCorpusIntro --output-format=colorized --exit-zero
  coverage:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: Install dependencies
        run: |
          scripts/install
      - name: Install coverage
        run: |
          pip install coverage
      - name: Run Coverage test
        run: |
          coverage run -m unittest discover
      - name: Test Coverage Result
        run: |
          coverage report -m